pipeline:
  name: test_prodsec_gs
  identifier: test_prodsec_gs
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  stages:
    - stage:
        name: Clone Repositories Stage
        identifier: Clone_Repos_Stage
        description: Cloning multiple repositories using matrix strategy
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: Clone Repositories
                  identifier: Clone_Repos
                  type: Run
                  strategy:
                    matrix:
                      maxConcurrency: 2
                      include:
                        - organization: harness
                          repository: ffproxy
                          repo_url: https://github.com/harness/ffproxy
                        - organization: harness
                          repository: lite-engine
                          repo_url: https://github.com/harness/lite-engine
                        - organization: drone
                          repository: drone-jira
                          repo_url: https://github.com/drone/drone-jira
                        - organization: drone
                          repository: drone-plugin-index
                          repo_url: https://github.com/drone/drone-plugin-index
                        - organization: takipi
                          repository: takipi-storage
                          repo_url: https://github.com/takipi/takipi-storage
                  spec:
                    shell: Bash
                    command: |
                      echo "Cloning repository <+matrix.organization>/<+matrix.repository> from <+matrix.repo_url>"
                      git clone <+matrix.repo_url>
                      if [ $? -ne 0 ]; then
                        echo "Failed to clone repository <+matrix.organization>/<+matrix.repository>"
                        exit 1
                      else
                        echo "Successfully cloned <+matrix.organization>/<+matrix.repository>"
                      fi
  properties:
    ci:
      codebase:
        connectorRef: test_GS_apphio
        repoName: test_app
        build: <+input>
        sparseCheckout: []
