pipeline:
  name: test_prodsec_gs
  identifier: test_prodsec_gs
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  variables:
    - name: SKIP_TESTS
      type: String
      value: "true"
  tags: {}
  stages:
    - stage:
        name: Semgrep Scan - Multiple repos
        identifier: Semgrep_Scan_Multiple_repos
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: Scan Repositories by Organization
                  identifier: Scan_repos_by_org
                  type: ShellScript
                  strategy:
                    matrix:
                      organization:
                        - name: harness
                          repositories:
                            - ffproxy
                            - lite-engine
                        - name: drone
                          repositories:
                            - drone-jira
                            - drone-plugin-index
                        - name: takipi
                          repositories:
                            - takipi-storage
                  spec:
                    shell: Bash
                    source:
                      type: Inline
                      spec:
                        script: |
                          echo "Processing organization: ${organization.name}"

                          # Loop over the repositories within the organization
                          for repo in "${organization.repositories[@]}"; do
                            echo "Cloning and scanning repository: ${organization.name}/${repo}"

                            git clone https://github.com/${organization.name}/${repo}.git
                            if [ $? -ne 0 ]; then
                                echo "Failed to clone repository ${organization.name}/${repo}. Skipping."
                                continue
                            fi

                            cd ${repo} || exit 1

                            # Fetch the default branch
                            default_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
                            echo "Default branch for ${repo} is ${default_branch}"

                            git checkout $default_branch

                            # Run Semgrep on the default branch
                            result_file="../${repo}_results.sarif"
                            semgrep ci --config auto --sarif -o $result_file

                            # Check if the results file was created
                            if [ -f "$result_file" ]; then
                                issues_count=$(jq '.runs[0].results | length' $result_file)
                                echo "Total issues found in ${repo}: $issues_count"
                            else
                                echo "No results file generated for ${repo}"
                            fi

                            # Cleanup
                            cd ..
                            rm -rf ${repo}
                          done
                    failureStrategies:
                      - onFailure:
                          errors:
                            - AllErrors
                          action:
                            type: MarkAsFailure
                    executionTarget: {}
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
        tags: {}
