pipeline:
  name: test_prodsec_gs
  identifier: test_prodsec_gs
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  stages:
    - stage:
        name: Debug Matrix Resolution
        identifier: Debug_Matrix_Resolution
        description: Testing if matrix variables are being passed correctly
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: Debug Matrix Variables
                  identifier: Debug_Matrix_Vars
                  type: Run
                  strategy:
                    matrix:
                      maxConcurrency: 1
                      include:
                        - org: harness
                          repo: ffproxy
                          url: https://github.com/harness/ffproxy
                        - org: harness
                          repo: lite-engine
                          url: https://github.com/harness/lite-engine
                        - org: drone
                          repo: drone-jira
                          url: https://github.com/drone/drone-jira
                        - org: drone
                          repo: drone-plugin-index
                          url: https://github.com/drone/drone-plugin-index
                        - org: takipi
                          repo: takipi-storage
                          url: https://github.com/takipi/takipi-storage
                  spec:
                    shell: Bash
                    command: |
                      echo "DEBUG: Organization: <+matrix.org>"
                      echo "DEBUG: Repository: <+matrix.repo>"
                      echo "DEBUG: Repo URL: <+matrix.url>"
                      if [ -z "<+matrix.url>" ]; then
                        echo "Repository URL is missing!"
                        exit 1
                      fi
                      echo "Matrix variables are working!"
