pipeline:
  name: semgrep-orch-test
  identifier: test_prodsec_gs
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: test_GS_apphio
        repoName: <+matrix.organization.name>/<+matrix.repository>
        build: <+input>
  stages:
    - stage:
        name: semgrep-orch
        identifier: semgreporch
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Semgrep
                  name: Semgrep_1
                  identifier: Semgrep_1
                  strategy:
                    matrix:
                      maxConcurrency: 2
                      organization:
                        - name: harness
                          repositories:
                            - ffproxy
                            - lite-engine
                        - name: drone
                          repositories:
                            - drone-jira
                            - drone-plugin-index
                        - name: takipi
                          repositories:
                            - takipi-storage
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                    reportName: Semgrep_Scan_Report
          reports:
            formats:
              - type: sarif
            upload: true
