pipeline:
  name: semgrep-orch-test
  identifier: test_prodsec_gs
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: test_GS_apphio
        repoName: test_GS
        build: <+input>
  stages:
    - stage:
        name: Semgrep Scan
        identifier: semgreporch
        description: Executing Semgrep scans across multiple repositories
        type: SecurityTests
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Semgrep
                  name: Semgrep Scan Step
                  identifier: semgrep_scan_step
                  strategy:
                    matrix:
                      maxConcurrency: 2
                      include:
                        - organization: harness
                          repositories:
                            - ffproxy
                            - lite-engine
                        - organization: drone
                          repositories:
                            - drone-jira
                            - drone-plugin-index
                        - organization: takipi
                          repositories:
                            - takipi-storage
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
