pipeline:
  name: test_prodsec_gs
  identifier: test_prodsec_gs
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  variables:
    - name: SKIP_TESTS
      type: String
      value: "true"
  stages:
    - stage:
        name: Semgrep Scan - Multiple repos
        identifier: Semgrep_Scan_Multiple_repos
        description: Scan multiple repositories using STO and Semgrep
        type: SecurityTests
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: Semgrep Scan with Matrix
                  identifier: Semgrep_Scan_Matrix
                  type: Semgrep
                  strategy:
                    matrix:
                      maxConcurrency: 2
                      organization:
                        - name: harness
                          repositories: ffproxy lite-engine
                        - name: drone
                          repositories: drone-jira drone-plugin-index
                        - name: takipi
                          repositories: takipi-storage
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                      target_name: <+matrix.organization.name>/<+matrix.repository>
                    advanced:
                      log:
                        level: info
                    repository:
                      connectorRef: github_connector_ref
                      repo: <+matrix.organization.name>/<+matrix.repository>
                      branch: ""
                    reportName: Semgrep_Scan_Report_<+matrix.repository>
          reports:
            formats:
              - type: sarif
            upload: true
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
