pipeline:
  name: test_prodsec_gs
  identifier: test_prodsec_gs
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  variables:
    - name: SKIP_TESTS
      type: String
      value: "true"
  tags: {}
  stages:
    - stage:
        name: Semgrep Scan - Multiple Repos
        identifier: Semgrep_Scan_Multiple_repos
        description: ""
        type: SecurityTests
        spec:
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: <K8S_CONNECTOR_REF>
              namespace: default
              resources:
                limits:
                  memory: 2048Mi
                  cpu: 1000m
          execution:
            steps:
              - step:
                  name: Semgrep Scan
                  identifier: Semgrep_Scan
                  type: Security
                  tool:
                    type: Semgrep
                  strategy:
                    matrix:
                      maxConcurrency: 2
                      organization:
                        - name: harness
                          repositories: ffproxy lite-engine
                        - name: drone
                          repositories: drone-jira drone-plugin-index
                        - name: takipi
                          repositories: takipi-storage
                  spec:
                    mode: orchestrated
                    config:
                      policy_type: Default
                      policy_config:
                        scan_type: full
                    source:
                      type: Git
                      spec:
                        connectorRef: <GIT_CONNECTOR_REF>
                        repoName: <+matrix.organization>/<+matrix.repository>
                        branch: main
                    advanced:
                      output_format: sarif
                    security:
                      severity:
                        - critical
                        - high
                        - medium
                        - low
                    envVariables:
                      - name: GITHUB_TOKEN
                        type: Secret
                        value: <YOUR_GITHUB_TOKEN>
                    reportName: Semgrep_Scan_Report
                timeout: 10m
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
        tags: {}
