pipeline:
  name: test_prodsec_gs
  identifier: test_prodsec_gs
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  variables:
    - name: SKIP_TESTS
      type: String
      value: "true"
  tags: {}
  stages:
    - stage:
        name: Semgrep Scan - Multiple repos
        identifier: Semgrep_Scan_Multiple_repos
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: STO Semgrep Scan
                  identifier: Sto_Semgrep_Scan
                  type: Semgrep
                  strategy:
                    matrix:
                      maxConcurrency: 2
                      include:
                        - organization: harness
                          repository: ffproxy
                          repo_url: https://github.com/harness/ffproxy
                        - organization: harness
                          repository: lite-engine
                          repo_url: https://github.com/harness/lite-engine
                        - organization: drone
                          repository: drone-jira
                          repo_url: https://github.com/drone/drone-jira
                        - organization: drone
                          repository: drone-plugin-index
                          repo_url: https://github.com/drone/drone-plugin-index
                        - organization: takipi
                          repository: takipi-storage
                          repo_url: https://github.com/takipi/takipi-storage
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                      target_name: <+matrix.repo_url>
                    advanced:
                      log:
                        level: info
                    repository:
                      connectorRef: github_connector_ref
                      repo: <+matrix.repo_url>
                      branch: ""
                    reportName: Semgrep_Scan_Report_<+matrix.repository>
          reports:
            formats:
              - type: sarif
            upload: true
          failureStrategies:
            - onFailure:
                errors:
                  - AllErrors
                action:
                  type: MarkAsFailure
