pipeline:
  name: semgrep-single-repo-scan
  identifier: test_prodsec_gs
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: test_GS_apphio
        repoName: takipi-storage
        build: <+input>
  stages:
    - stage:
        name: Semgrep Scan
        identifier: semgrep_scan_stage
        description: Scanning a single repository using Semgrep
        type: SecurityTests
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Semgrep
                  name: Semgrep Scan Step
                  identifier: semgrep_scan_step
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
