pipeline:
  name: test_prodsec_gs
  identifier: test_prodsec_gs
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  stages:
    - stage:
        name: Clone Repositories Stage
        identifier: Clone_Repos_Stage
        description: Cloning multiple repositories using matrix strategy
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: Clone Repositories and List Contents
                  identifier: Clone_Repos_And_LS
                  type: Run
                  strategy:
                    matrix:
                      maxConcurrency: 2
                      include:
                        - organization: harness
                          repository: ffproxy
                          repo_url: https://github.com/harness/ffproxy
                        - organization: harness
                          repository: lite-engine
                          repo_url: https://github.com/harness/lite-engine
                        - organization: drone
                          repository: drone-jira
                          repo_url: https://github.com/drone/drone-jira
                        - organization: drone
                          repository: drone-plugin-index
                          repo_url: https://github.com/drone/drone-plugin-index
                        - organization: takipi
                          repository: takipi-storage
                          repo_url: https://github.com/takipi/takipi-storage
                  spec:
                    connectorRef: test_GS_apphio
                    shell: Bash
                    command: |
                      echo "Cloning repository <+matrix.organization>/<+matrix.repository> from <+matrix.repo_url>"

                      git clone <+matrix.repo_url>
                      if [ $? -ne 0 ]; then
                        echo "Failed to clone repository <+matrix.organization>/<+matrix.repository>"
                        exit 1
                      else
                        echo "Successfully cloned <+matrix.organization>/<+matrix.repository>"
                      fi

                      # Navigate into the repository folder and list its contents
                      repo_dir="<+matrix.repository>"
                      if [ -d "$repo_dir" ]; then
                        echo "Listing contents of <+matrix.repository>:"
                        ls "$repo_dir"
                      else
                        echo "Directory <+matrix.repository> does not exist. Clone might have failed."
                      fi
