pipeline:
  name: semgrep-orch-test
  identifier: test_prodsec_gs
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Semgrep Scan - Multiple Repos
        identifier: semgrep_scan_multiple_repos
        description: Scanning multiple repositories using Semgrep
        type: SecurityTests
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Semgrep
                  name: Semgrep_Scan
                  identifier: Semgrep_Scan
                  strategy:
                    matrix:
                      maxConcurrency: 2
                      include:
                        - organization: harness
                          repository: ffproxy
                          repo_url: https://github.com/gunwantsingh-harness/harness/ffproxy
                        - organization: harness
                          repository: lite-engine
                          repo_url: https://github.com/gunwantsingh-harness/harness/lite-engine
                        - organization: drone
                          repository: drone-jira
                          repo_url: https://github.com/gunwantsingh-harness/drone/drone-jira
                        - organization: drone
                          repository: drone-plugin-index
                          repo_url: https://github.com/gunwantsingh-harness/drone/drone-plugin-index
                        - organization: takipi
                          repository: takipi-storage
                          repo_url: https://github.com/gunwantsingh-harness/takipi/takipi-storage
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                      target_name: <+matrix.repo_url>
                    advanced:
                      log:
                        level: info
                    repository:
                      connectorRef: test_app_apphio
                      repo: <+matrix.repo_url>
                      branch: ""
                    reportName: Semgrep_Scan_Report
          reports:
            formats:
              - type: sarif
            upload: true
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
