pipeline:
  name: semgrep-orch-test
  identifier: test_prodsec_gs
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Semgrep Scan - Single Repo
        identifier: semgrep_scan_single_repo
        description: Scanning a single repository using Semgrep
        type: SecurityTests
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Semgrep
                  name: Semgrep_Scan
                  identifier: Semgrep_Scan
                  strategy:
                    matrix:
                      include:
                        - organization: takipi
                          repository: takipi-storage
                          repo_url: https://github.com/takipi/takipi-storage
                          target_name: takipi-storage
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                      target_name: <+matrix.target_name>
                    advanced:
                      log:
                        level: info
                    repository:
                      connectorRef: test_app_apphio
                      repo: <+matrix.repo_url>
                      branch: ""
                    reportName: Semgrep_Scan_Report
          reports:
            formats:
              - type: sarif
            upload: true
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
