pipeline:
  name: semgrep-simple-scan
  identifier: test_prodsec_gs
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: test_GS_apphio
        repoName: harness/ffproxy
        branch: main
        build: <+input>
  stages:
    - stage:
        name: Semgrep Scan - Multiple Repos
        identifier: semgrep_scan
        description: Scanning multiple repositories using Semgrep
        type: SecurityTests
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Semgrep
                  name: Scan ffproxy Repository
                  identifier: scan_ffproxy
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                      target_name: harness/ffproxy
                    advanced:
                      log:
                        level: info
                    repository:
                      repo: harness/ffproxy
                      branch: ""
                    reportName: Semgrep_Scan_ffproxy_Report
              - step:
                  type: Semgrep
                  name: Scan lite-engine Repository
                  identifier: scan_lite_engine
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                      target_name: harness/lite-engine
                    advanced:
                      log:
                        level: info
                    repository:
                      repo: harness/lite-engine
                      branch: ""
                    reportName: Semgrep_Scan_lite_engine_Report
          reports:
            formats:
              - type: sarif
            upload: true
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: MarkAsFailure
