pipeline:
  name: test_prodsec_gs
  identifier: test_prodsec_gs
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  variables:
    - name: SKIP_TESTS
      type: String
      value: "true"
  stages:
    - stage:
        name: Debug Matrix
        identifier: Debug_Matrix_Stage
        description: Debug matrix variable usage
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: Debug Matrix Variables
                  identifier: Debug_Matrix_Vars
                  type: Run
                  strategy:
                    matrix:
                      include:
                        - orgName: harness
                          repoName: ffproxy
                          repoUrl: https://github.com/harness/ffproxy
                        - orgName: harness
                          repoName: lite-engine
                          repoUrl: https://github.com/harness/lite-engine
                        - orgName: drone
                          repoName: drone-jira
                          repoUrl: https://github.com/drone/drone-jira
                        - orgName: drone
                          repoName: drone-plugin-index
                          repoUrl: https://github.com/drone/drone-plugin-index
                        - orgName: takipi
                          repoName: takipi-storage
                          repoUrl: https://github.com/takipi/takipi-storage
                  spec:
                    shell: Bash
                    command: |
                      echo "DEBUG: Organization: <+matrix.orgName>"
                      echo "DEBUG: Repository: <+matrix.repoName>"
                      echo "DEBUG: Repo URL: <+matrix.repoUrl>"
                      if [ -z "<+matrix.repoUrl>" ]; then
                        echo "Repository URL is missing!"
                        exit 1
                      fi
                      echo "Matrix is working!"
