pipeline:
  name: test_prodsec_gs
  identifier: test_prodsec_gs
  projectIdentifier: Security_Test_Scans
  orgIdentifier: default
  stages:
    - stage:
        name: Clone and Scan Repositories
        identifier: Clone_Scan_Repos
        description: Manually define steps for each repository
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  name: Clone ffproxy Repo
                  identifier: Clone_ffproxy
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "Cloning repository harness/ffproxy"
                      git clone https://github.com/harness/ffproxy
                      # Add Semgrep or other steps as needed
              - step:
                  name: Clone lite-engine Repo
                  identifier: Clone_lite_engine
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "Cloning repository harness/lite-engine"
                      git clone https://github.com/harness/lite-engine
                      # Add Semgrep or other steps as needed
              - step:
                  name: Clone drone-jira Repo
                  identifier: Clone_drone_jira
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "Cloning repository drone/drone-jira"
                      git clone https://github.com/drone/drone-jira
                      # Add Semgrep or other steps as needed
              - step:
                  name: Clone drone-plugin-index Repo
                  identifier: Clone_drone_plugin_index
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "Cloning repository drone/drone-plugin-index"
                      git clone https://github.com/drone/drone-plugin-index
                      # Add Semgrep or other steps as needed
              - step:
                  name: Clone takipi-storage Repo
                  identifier: Clone_takipi_storage
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "Cloning repository takipi/takipi-storage"
                      git clone https://github.com/takipi/takipi-storage
                      # Add Semgrep or other steps as needed
  properties:
    ci:
      codebase:
        connectorRef: test_GS_apphio
        repoName: test_app
        build: <+input>
        sparseCheckout: []
